services:
  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost_test
    restart: unless-stopped
    environment:
      database__client: mysql
      database__connection__host: ${AIVEN_MYSQL_HOST}
      database__connection__port: ${AIVEN_MYSQL_PORT}
      database__connection__user: ${AIVEN_MYSQL_USER}
      database__connection__password: ${AIVEN_MYSQL_PASSWORD}
      database__connection__database: ${AIVEN_MYSQL_DATABASE}
      url: https://${GHOST_HOST}
      
      storage__active: ghost-storage-cloudinary
      storage__ghost_storage_cloudinary__cloud_name: ${CLOUDINARY_CLOUD_NAME}
      storage__ghost_storage_cloudinary__api_key: ${CLOUDINARY_API_KEY}
      storage__ghost_storage_cloudinary__api_secret: ${CLOUDINARY_API_SECRET}

    volumes:
-     - "../files/ghost_test_persist/content:/var/lib/ghost/content"
+     - "ghost_content:/var/lib/ghost/content"  # 使用命名卷

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${GHOST_HOST}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost.middlewares=set-x-forwarded-proto@file"

# 新增全局卷声明
+volumes:
+  ghost_content:
+    driver: local
+    driver_opts:
+      type: none
+      o: bind
+      device: /etc/dokploy/compose/${COMPOSE_PROJECT_NAME}/files/ghost_content  # Dokploy 标准路径