# docker-compose.yml
services:
  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost_test
    restart: unless-stopped
    environment:
      database__client: mysql
      database__connection__host: ${AIVEN_MYSQL_HOST}
      database__connection__port: ${AIVEN_MYSQL_PORT}
      database__connection__user: ${AIVEN_MYSQL_USER}
      database__connection__password: ${AIVEN_MYSQL_PASSWORD}
      database__connection__database: ${AIVEN_MYSQL_DATABASE}
      url: https://${GHOST_HOST}
      
      # 必须使用双下划线层级结构
      storage__active: ghost-storage-cloudinary
      storage__ghost_storage_cloudinary__cloud_name: ${CLOUDINARY_CLOUD_NAME}
      storage__ghost_storage_cloudinary__api_key: ${CLOUDINARY_API_KEY}
      storage__ghost_storage_cloudinary__api_secret: ${CLOUDINARY_API_SECRET}

    volumes:
      # 仅挂载配置目录（解决插件丢失问题）
      - "../files/ghost_test_persist/content/settings:/var/lib/ghost/content/settings"

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${GHOST_HOST}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost.middlewares=set-x-forwarded-proto@file"
