services:
  ghost:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ghost_test 
    restart: always
    environment:
      database__client: mysql
      database__connection__host: ${AIVEN_MYSQL_HOST}
      database__connection__port: ${AIVEN_MYSQL_PORT}
      database__connection__user: ${AIVEN_MYSQL_USER}
      database__connection__password: ${AIVEN_MYSQL_PASSWORD}
      database__connection__database: ${AIVEN_MYSQL_DATABASE}
      url: https://${GHOST_HOST}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
    # 修正卷挂载配置（关键修复）
    volumes:
      - ghost_data:/var/lib/ghost/content
      - ghost_content_persist:/var/lib/ghost/content-persist
    # 添加用户映射（重要）
    user: "node" 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ghost.rule=Host(`${GHOST_HOST}`)"
      - "traefik.http.routers.ghost.entrypoints=websecure"
      - "traefik.http.routers.ghost.tls=true"
      - "traefik.http.services.ghost.loadbalancer.server.port=2368"
      - "traefik.http.routers.ghost.middlewares=set-x-forwarded-proto@file"

volumes:
  ghost_data:
  ghost_content_persist:
